### ISSUE TITLE
Images are not shown

### ISSUE THREAD

**Issue by HugoGranstrom** [SciNim/getting-started#16] opened 2021-06-04 14:22 UTC
Look here: https://scinim.github.io/getting-started/data_viz/basic_plotting.html The images are not loaded. This is because they are saved at `nbHomeDir/images` while the HTML file looks as `nbHomeDir/data_viz/images`. This is because the currentDir has been changed to `nbHomeDir` and the script just saves it at `images/img.png`. So we either change the saving (clutters the code the viewer sees) or we use nbHomeDir when we load the image with `nbImage` like this:
```nim
nbImage(nbHomeDir / "images/img.png")
```

But `nimib/path` isn't exported to us by default...
My naive try at a solution using absolute paths didn't work. Maybe we need the path to the image to be relative?

**Comment by HugoGranstrom** [comment] 2021-06-04 14:59
The easiest solution seems to be to just save the images in the correct place from the beginning 🤷 so in this case: `ggsave("data_viz/images/img.png")`

**Comment by pietroppeter** [comment] 2021-06-04 15:27
this in the end I think it should be an issue in nimib that we should solve upstream. I will create an issue.

the problem is that the path created by `nbImage` does not correctly takes into account relative path from current document to `nbHomeDir` (what in mdbook/nimibook is called `path_to_root`).
Instead of producing: `<img src="images/line_plot.png" alt="">` its should produce `<img src="../images/line_plot.png" alt="">`.

the workaround you propose for the fix creates two different paths for saving and reading and it will break if you move basic_plotting.nim in a different folder.

**Comment by pietroppeter** [comment] 2021-06-04 15:31
> But nimib/path isn't exported to us by default...

`nimib / paths` is indeed exported by default when you import `nimib`. I think something like `nbHomeDir / "images/img.png".RelativeDir` should work. The problem is I fear it is not the correct solution for the issue (I always have to think 20 minutes about this path things, that is why I would like so much to have an api that prevents this mistakes).

**Comment by HugoGranstrom** [comment] 2021-06-04 16:07
> this in the end I think it should be an issue in nimib that we should solve upstream. I will create an issue.
>
> the problem is that the path created by nbImage does not correctly takes into account relative path from current document to nbHomeDir (what in mdbook/nimibook is called path_to_root).
Instead of producing: <img src="images/line_plot.png" alt=""> its should produce <img src="../images/line_plot.png" alt="">.

Nice, thank you 👍 Yes, something along those lines should work. 

> the workaround you propose for the fix creates two different paths for saving and reading and it will break if you move basic_plotting.nim in a different folder.

That is correct, luckily one doesn't move files that often but yes it's not optimal. It's a silent error as well (it's only when we try to run the HTML we notice it) so some form of a check that the path exists perhaps? That's useful in general as well. But that would also limit the flexibility perhaps in loading images that other files have created (or will create in the future when they are compiled). 

 > nimib / paths is indeed exported by default when you import nimib. I think something like nbHomeDir / "images/img.png".RelativeDir should work. The problem is I fear it is not the correct solution for the issue (I always have to think 20 minutes about this path things, that is why I would like so much to have an api that prevents this mistakes).

😅 yeah don't know where I got that from, it does work now... 
I think we have to limit ourselves to relative paths for images or at least convert it to a relative path internally. HTML doesn't like absolute paths (security reasons I guess). 
Hehe yeah there are so many different paths as well saved in different places so it can be hard to know exactly which one to use sometimes. Do you have an idea of how you want the paths to work in the future to solve (most of) all this?

**Comment by HugoGranstrom** [comment] 2021-06-10 09:53
Will hopefully be closed by https://github.com/pietroppeter/nimib/pull/56

**Comment by pietroppeter** [comment] 2021-06-10 10:21
merged and v0.1.4 released!

**Comment by HugoGranstrom** [comment] 2021-06-10 10:35
Rerunning the deployment now. 

And it worked! https://scinim.github.io/getting-started/data_viz/basic_plotting.html

**Closed** 2021-06-10 10:36 UTC
